spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employee_system
    username: "root"
    password: "123456786"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true